---
title: "Analysis"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


This document contains a series of steps that the project members have performed to explore the Geo-PKO dataset. 

Load packages.
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(readr)
library(ggthemes)
```
Import the dataset. 

```{r, warning=FALSE, message =FALSE}
GeoPKO <- read_csv("data/geopko.csv")
```

Now we can start with the actual fun stuff! Let's have a quick look at the first few rows of the dataset.
 
```{r}
head(GeoPKO)
```

```{r}
NoMission <- GeoPKO %>% select(year, Mission) %>% distinct(year, Mission) %>% count(year)
Plot1 <- ggplot(NoMission, aes(x=(as.numeric(year)), y=n)) + geom_point() + geom_line(size=0.5) +
  scale_x_continuous("Year", breaks=seq(1994, 2018, 1))+theme_classic()+
  scale_y_continuous("Number of missions", breaks=seq(0,10,1)) +
  theme(panel.grid=element_blank(), 
        axis.text.x=element_text(angle=45, vjust=0.5)) +
  ggtitle("Number of UN Peacekeeping Missions in Africa, 1994-2018")
Plot1

```

